### ISSUE TITLE
can't create account

### ISSUE THREAD

**Issue by samizy** [Sreelal-c/Online-Job-Portal#12]
am having difficulties registering as a 'job seeker' or 'employer'.
i get this error: error code:404. error message:not found.

country, state and city not fetching from database.

**Comment by Sreelal-c** [comment]
You should first import the sql files 'location.sql' and 'jobportal.sql' using phpmyadmin or alternative.
I may solve your problem.

**Comment by samizy** [comment]
i already imported the sql files but it still not working. 
i still get this error :  "error code:404. error message:not found" each time i click on "jobseeker" or "employer"

i cannot select location, its not fetching the options from the database. please how do i solve this problem? thanks.

**Comment by Sreelal-c** [comment]
Have you changed the username and password of your database in "location/classes/dbconfig.php" file

**Comment by samizy** [comment]
yes its now working, but i get this error: Unknown column 'admin' in 'where clause' when i try to log in to the admin page

**Comment by Sreelal-c** [comment]
Admin login is working though its functions are incomplete. Need to check for this issue!
